### ISSUE TITLE
Webilder can't download images on KDE4.4.2

### ISSUE THREAD

**Issue by BostonPeng** [thesamet/webilder#2]
After using Webilder on a GNOME-based system for quite some time I recently switched to running a KDE-based system. I was able to get Webilder running but when I try to run the downloader it crashed almost immediately.

Here's my terminal output:

:~$ webilder_downloader 
Downloading list of photos (may take some time) 
url =  http://api.flickr.com/services/rest/?sort=interestingness-desc&extras=original_format&tag_mode=all&tags=bikini%2Cwallpaper&per_page=20&api_key=045379bc5368502f749af23d95a17c83&method=flickr.photos.search
Traceback (most recent call last):
  File "/usr/bin/webilder_downloader", line 9, in <module>
    load_entry_point('Webilder==0.6.7', 'console_scripts', 'webilder_downloader')()
  File "/usr/lib/python2.6/dist-packages/webilder/downloader.py", line 195, in main
    download_all(notify)
  File "/usr/lib/python2.6/dist-packages/webilder/downloader.py", line 150, in download_all
    photos = get_full_download_list(config)
  File "/usr/lib/python2.6/dist-packages/webilder/downloader.py", line 26, in get_full_download_list
    photos = module.get_download_list(config_obj)
  File "/usr/lib/python2.6/dist-packages/webilder/flickr/**init**.py", line 51, in get_download_list
    photos = flickr.photos_search(**params_dict) # pylint: disable=W0142
  File "/usr/lib/python2.6/dist-packages/webilder/flickr/flickrapi.py", line 46, in photos_search
    return self.make_photo_list(photos)
AttributeError: 'FlickrProxy' object has no attribute 'make_photo_list'
:~$ 

I'm running Webilder 0.6.3-1 (built from source) KDE 4.4.2 on top of Ubuntu 10.04.

**Comment by thesamet** [comment]
This problem has been fixed on 0.6.8 which I uploaded to the website yesterday.

**Comment by BostonPeng** [comment]
I can confirm the fix resolved the issue. Thanks!
