### ISSUE TITLE
Webilder 0.6.7 won't download photos Ubuntu 10.04 Gnome

### ISSUE THREAD

**Issue by bhupi** [thesamet/webilder#4]
Here is the output I get from running webilder_desktop at command line and then hitting the download button:

url =  http://api.flickr.com/services/rest/?sort=interestingness-desc&extras=original_format&tag_mode=all&tags=1600x1200%2Cwallpaper&per_page=20&api_key=045379bc5368502f749af23d95a17c83&method=flickr.photos.search
Thread done
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in **bootstrap_inner
    self.run()
  File "/usr/lib/pymodules/python2.6/webilder/progress_dialog.py", line 48, in newfunc
    func(self, _args, *_kwargs)
  File "/usr/lib/pymodules/python2.6/webilder/DownloadDialog.py", line 35, in run
    terminate = self.should_terminate)
  File "/usr/lib/pymodules/python2.6/webilder/downloader.py", line 150, in download_all
    photos = get_full_download_list(config)
  File "/usr/lib/pymodules/python2.6/webilder/downloader.py", line 26, in get_full_download_list
    photos = module.get_download_list(config_obj)
  File "/usr/lib/pymodules/python2.6/webilder/flickr/__init**.py", line 51, in get_download_list
    photos = flickr.photos_search(**params_dict) # pylint: disable=W0142
  File "/usr/lib/pymodules/python2.6/webilder/flickr/flickrapi.py", line 46, in photos_search
    return self.make_photo_list(photos)
AttributeError: 'FlickrProxy' object has no attribute 'make_photo_list'

**Comment by thesamet** [comment]
Thanks for reporting this. It's fixed in Webilder 0.6.8 which I pushed today to the website. 
(commit cdae48c5394634223df5e86d8695e2e26844b70f)

**Comment by bhupi** [comment]
For some reason I can never get webilder to work if I download the zip file, extract and install with: sudo python setup.py install --prefix=/usr.  I get these errors:  webilder_desktop
Traceback (most recent call last):
  File "/usr/bin/webilder_desktop", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2659, in <module>
    parse_requirements(**requires**), Environment()
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Webilder==0.6.8

The GetDeb install distribution works for me.

**Comment by thesamet** [comment]
Turns out that the --prefix=/usr does not work well in Ubuntu. The right prefix should be /usr/local.

Unfortunately, there isn't an easy way to clean up the previous installation, but the next manual install will show you the list of files under the new prefix so you can figure it out.

The updated installation instructions are on: http://www.webilder.org/download.html
