### ISSUE TITLE
HTTP error 403 (Forbidden) when downloading photos

### ISSUE THREAD

**Issue by kristofwillen** [thesamet/webilder#48]
Webilder fails to download new images since a few days : 

$ /usr/bin/python /usr/bin/webilder_desktop
url =  http://api.flickr.com/services/rest/?sort=interestingness-desc&extras=original_format&tag_mode=all&tags=nature&per_page=20&api_key=045379bc5368502f749af23d95a17c83&method=flickr.photos.search
Thread done
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/pymodules/python2.7/webilder/progress_dialog.py", line 48, in newfunc
    func(self, _args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/webilder/DownloadDialog.py", line 51, in run
    raise exc
HTTPError: HTTP Error 403: Forbidden

This can be solved by changing /usr/share/pyshared/webilder/flickr/flickrapi.py and replace the http entry to https.

**Comment by rharing** [comment]
thx for that info, that solved it for me as well.

Regards
Ronald

**Comment by thesamet** [comment]
Fixed in 0.7.3.

**Comment by ermundim** [comment]
I've instaled 0.7.3 on ubuntu 14. When I lanch webilde_downloader, I see
url =  http://api.flickr.com/services/rest/?per_page=20&extras=original_format&method=flickr.interestingness.getList&api_key=045379bc5368502f749af23d95a17c83
Traceback (most recent call last):
  File "/usr/local/bin/webilder_downloader", line 9, in <module>
    load_entry_point('Webilder==0.7.2', 'console_scripts', 'webilder_downloader')()
  File "/usr/local/lib/python2.7/dist-packages/webilder/downloader.py", line 195, in main
    download_all(notify)
  File "/usr/local/lib/python2.7/dist-packages/webilder/downloader.py", line 150, in download_all
    photos = get_full_download_list(config)
  File "/usr/local/lib/python2.7/dist-packages/webilder/downloader.py", line 26, in get_full_download_list
    photos = module.get_download_list(config_obj)
  File "/usr/local/lib/python2.7/dist-packages/webilder/flickr/**init**.py", line 58, in get_download_list
    extras='original_format')
  File "/usr/local/lib/python2.7/dist-packages/webilder/flickr/flickrapi.py", line 50, in interestingness_search
    photos = self.call('flickr.interestingness.getList', *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webilder/flickr/flickrapi.py", line 32, in call
    resp = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
