### ISSUE TITLE
 webilder-0.7.3 0 : webilder_downloader - UnicodeEncodeError

### ISSUE THREAD

**Issue by Corin-EU** [thesamet/webilder#53]
webilder-0.7.3

webilder_downlloader exits with an error on a non-ASCII character when retriveing content:

```
url =  https://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=16929226431&method=flickr.photos.getSizes
Traceback (most recent call last):
  File "/usr/local/bin/webilder_downloader", line 9, in <module>
    load_entry_point('Webilder==0.7.3', 'console_scripts', 'webilder_downloader')()
  File "/usr/local/lib/python2.7/dist-packages/webilder/downloader.py", line 195, in main
    download_all(notify)
  File "/usr/local/lib/python2.7/dist-packages/webilder/downloader.py", line 154, in download_all
    filter_photos(config, photos)
File "/usr/local/lib/python2.7/dist-packages/webilder/downloader.py", line 87, in filter_photos
    print _("Skipping non-landscape photo '%s'") % photo['title']
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 54: ordinal not in range(128)
```

Can something be done to fix this problem?

**Comment by Corin-EU** [comment]
Over two years later and photographs can still not be downloaded from Flickr because the unicode issue  is still to be fixed.

    url =  https://api.flickr.com/services/rest/?api_key=045379bc5368502f749af23d95a17c83&photo_id=34721603982&method=flickr.photos.getSizes
       Traceback (most recent call last):
       File "/usr/local/bin/webilder_downloader", line 9, in <module>
       load_entry_point('Webilder==0.7.3', 'console_scripts', 'webilder_downloader')()
       File "/usr/local/lib/python2.7/dist-packages/webilder/downloader.py", line 195, in main     download_all(notify)
       File "/usr/local/lib/python2.7/dist-packages/webilder/downloader.py", line 154, in download_all
    filter_photos(config, photos)
       File "/usr/local/lib/python2.7/dist-packages/webilder/downloader.py", line 87, in filter_photos
       print _("Skipping non-landscape photo '%s'") % photo['title']
       UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 116: ordinal not in range(128)

It appears that this project has been abandoned.

**Comment by thesamet** [comment]
Hey Corin, yes - I am unable to work on this project at this point. Pull requests are welcome.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @Corin-EU)
